/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import CSDL.tbLophoc;
import CSDL.tbSinhvien;
import Models.clsLophoc;
import Models.clsSinhvien;
import java.io.File;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Manh Truong
 */
public class frmQuanlySinhvien extends javax.swing.JFrame {

    /**
     * Creates new form frmQuanlySinhvien
     */
    public frmQuanlySinhvien() {
        initComponents();
        HienthiDSSinhvien();
    }
    public void HienthiDSSinhvien()
    {
        tbSinhvien bangSinhvien = new tbSinhvien();
        Vector<clsSinhvien> dsSinhvien = bangSinhvien.LayDSSinhvien();
        if(dsSinhvien.size()>0)
        {
            DefaultTableModel dtm = (DefaultTableModel)tblDSSinhvien.getModel();
            dtm.setRowCount(0);//xóa các dòng cũ nếu có
            for(clsSinhvien sv : dsSinhvien)
            {
                String gioitinh = (sv.gioitinh)?"Nam":"Nữ";
                //lấy tên lớp học trong csdl từ mã lớp
                //tbLophoc bangLophoc = new tbLophoc();
                //String tenlop = bangLophoc.LayTenLop(sv.malop);
               
             dtm.addRow(new Object[]{sv.id,sv.masv,sv.hoten,gioitinh,sv.diachi,sv.malop,sv.tenlop,sv.hinhanh});
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        bnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSSinhvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtDiachi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbLophoc = new javax.swing.JComboBox<>();
        lblHinhanh = new javax.swing.JLabel();
        lblTenAnh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        btThem.setText("THÊM");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btSua.setText("SỬA");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        bnXoa.setText("XÓA");
        bnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXoaActionPerformed(evt);
            }
        });

        tblDSSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Mã sv", "Họ tên", "Giới tính", "Địa chỉ", "Mã lớp", "Lớp học", "Hình ảnh"
            }
        ));
        tblDSSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSSinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSSinhvien);

        jLabel2.setText("Mã sinh viên:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Giới tính:");

        rdNam.setSelected(true);
        rdNam.setText("Nam");

        rdNu.setText("Nữ");

        jLabel5.setText("Địa chỉ:");

        jLabel6.setText("Lớp học:");

        lblHinhanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        lblTenAnh.setText("Hinh anh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdNam)
                                        .addGap(31, 31, 31)
                                        .addComponent(rdNu))
                                    .addComponent(txtDiachi)
                                    .addComponent(txtHoten)
                                    .addComponent(txtMaSV)
                                    .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblTenAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bnXoa))
                        .addComponent(btSua, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btThem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rdNam)
                            .addComponent(rdNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbLophoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenAnh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int i = tblDSSinhvien.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            clsSinhvien sv = new clsSinhvien();
            sv.id = (int)tblDSSinhvien.getModel().getValueAt(i,0);
            sv.masv = (String)tblDSSinhvien.getModel().getValueAt(i,1);
            sv.hoten = (String)tblDSSinhvien.getModel().getValueAt(i,2);
            String gioitinh = (String)tblDSSinhvien.getModel().getValueAt(i,3);
            sv.gioitinh = (gioitinh.equals("Nam"))?true:false;
            sv.diachi = (String)tblDSSinhvien.getModel().getValueAt(i,4);
            sv.malop = (int)tblDSSinhvien.getModel().getValueAt(i,5);
            String tenlop = (String)tblDSSinhvien.getModel().getValueAt(i,6);
            sv.hinhanh = (String)tblDSSinhvien.getModel().getValueAt(i,7);
            frmSuaSV csSuaSV = new frmSuaSV();
            csSuaSV.sinhvien = sv;
            csSuaSV.gioitinh = gioitinh;
            csSuaSV.tenlop = tenlop;
            csSuaSV.formQuanlySV = this;
            csSuaSV.setVisible(true);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        frmThemSV formThemSV = new frmThemSV();
        formThemSV.formQuanlySV = this;
        formThemSV.setVisible(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void bnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXoaActionPerformed
        // TODO add your handling code here:
        int i = tblDSSinhvien.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            int id;
            id = (int)tblDSSinhvien.getModel().getValueAt(i,0);
            tbSinhvien bangSinhvien = new tbSinhvien();
            boolean kq = bangSinhvien.XoaSinhvien(id);
            if(kq==true)
            {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                HienthiDSSinhvien();
            }
            else
                JOptionPane.showMessageDialog(this, "Lỗi xóa sinh viên");
        }
    }//GEN-LAST:event_bnXoaActionPerformed

    private void tblDSSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSSinhvienMouseClicked
        // TODO add your handling code here:
        int i = tblDSSinhvien.getSelectedRow();
        if(i<0)
            JOptionPane.showMessageDialog(this, "Chưa chọn sinh viên");
        else
        {
            //lấy thông tin từ dòng chọn trong JTable
            clsSinhvien sv = new clsSinhvien();
            sv.id = (int)tblDSSinhvien.getModel().getValueAt(i,0);
            sv.masv = (String)tblDSSinhvien.getModel().getValueAt(i,1);
            sv.hoten = (String)tblDSSinhvien.getModel().getValueAt(i,2);
            String gioitinh = (String)tblDSSinhvien.getModel().getValueAt(i,3);
            sv.gioitinh = (gioitinh.equals("Nam"))?true:false;
            sv.diachi = (String)tblDSSinhvien.getModel().getValueAt(i,4);
            sv.malop = (int)tblDSSinhvien.getModel().getValueAt(i,5);
            String tenlop = (String)tblDSSinhvien.getModel().getValueAt(i,6);
            Object objAnh = tblDSSinhvien.getModel().getValueAt(i,7);
            if(objAnh!=null)
                sv.hinhanh = (String) objAnh;
            else
                sv.hinhanh ="";
            //hiển thị lên form
            txtMaSV.setText(sv.masv);
            txtHoten.setText(sv.hoten);
            txtDiachi.setText(sv.diachi);
            if(sv.gioitinh==true)
                rdNam.setSelected(true);
            else
                rdNu.setSelected(true);

            clsTienich.ComboBoxLophoc(cbLophoc,0);
            cbLophoc.getModel().setSelectedItem(tenlop);
            //hiển thị anh từ tên tệp vào lable
            //JOptionPane.showMessageDialog(null, "do dai:" +sv.hinhanh.length());
            if(sv.hinhanh.equals("")==false)
            {
                //JOptionPane.showMessageDialog(null, "test1");
                lblTenAnh.setText(sv.hinhanh);
                File fileAnh = new File("src/images/"+sv.hinhanh);
                clsTienich.HienthiAnh_Label(fileAnh, lblHinhanh);
                
            }
            else
            {
                //JOptionPane.showMessageDialog(null, "test2");
                lblTenAnh.setText("");
                lblHinhanh.setIcon(null);
                //clsTienich.HienthiAnh_Label(null, lblHinhanh);
            }
            }
    }//GEN-LAST:event_tblDSSinhvienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuanlySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuanlySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuanlySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuanlySinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuanlySinhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnXoa;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JComboBox<String> cbLophoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhanh;
    private javax.swing.JLabel lblTenAnh;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tblDSSinhvien;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaSV;
    // End of variables declaration//GEN-END:variables
}
